

# Ejemplo de Makefile hecho muy apurado, no se cuales son las exigencias exactas del tp, por eso no lo deje
# CC = gcc
# CFLAGS = -Wall -std=c2x
# TARGET = prog
# SRCS = main.c tabla.c conversion.c
# OBJS = $(SRCS:.c=.o)

# $(TARGET): $(OBJS)
# 	$(CC) $(CFLAGS) -o $(TARGET) $(OBJS)

# main.o: main.c tabla.h
# 	$(CC) $(CFLAGS) -c main.c

# tabla.o: tabla.c tabla.h conversion.h
# 	$(CC) $(CFLAGS) -c tabla.c

# conversion.o: conversion.c conversion.h
# 	$(CC) $(CFLAGS) -c conversion.c

# clean:
# 	rm -f $(OBJS) $(TARGET)
